### ISSUE TITLE
Use ProjectQ _time_evolution

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion-ProjectQ#10]
In order to avoid ProjectQ rejecting instances of QubitOperator coming from OpenFermion, we moved the entire _time_evolution.py code from ProjectQ into OpenFermion-ProjectQ. But this seems like a suboptimal solution. Is there some change that can be made to _time_evolution in ProjectQ or to QubitOperator in OpenFermion which would allow us to avoid this duplication of code? @damiansteiger @idk3 @thomashaener any ideas?

**Comment by thomashaener** [comment]
Sure, just use TimeEvolution and QubitOperator from ProjectQ. One way to do this is to provide a conversion function which, given a non-ProjectQ QubitOperator, returns the corresponding ProjectQ QubitOperator. At some point, the two implementations might diverge, so having a conversion function is a huge plus as it is the only piece of code that would need to be changed.

**Comment by babbush** [comment]
I think the suggestion is to have a function, e.g. "convert_operator()" which takes an instance of the OpenFermion QubitOperator as input and outputs an instance of the ProjectQ QubitOperator. This is a technical solution but it seems clunky to need to write
TimeEvolution(time, convert_operator(my_qubit_operator)) | register
It would be much better if we could somehow write:
TimeEvolution(time, my_qubit_operator) | register
and just have it work.

What if I make an OpenFermion function called "TimeEvolution" with the same signature as the initiator for TimeEvolution, which returns projectq.ops.TimeEvolution(time, convert_operator(my_qubit_operator)). Would that work?

**Comment by babbush** [comment]
Great, I've done that. Thanks!
