### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion-ProjectQ#11]
The reason test coverage is so low is that there appear to be problems on the simulator end when running tests in _ffft_test.py and _low_depth_trotter_simulation_test.py. We should "unskip" those tests one by one, track down the offending tests, and figure out why they are failing, then stop them. Once these tests are back we should be in excess of 99% test coverage again.

**Comment by babbush** [comment]
I've unskipped many of the tests and left the ones that pass. It seems that only a couple tests in _ffft_test raise an error. The rest just seg fault. @idk3 reports that on a clear mac installation all of the _low_depth_trotter_simulation_test tests pass. But it seg faults for me and others on Linux and also seg faults for Travis. @idk3 can you report what version of the ProjectQ simulator you are using? Is it the C++ version or python?

@thomashaner and @damiansteiger do you guys have any idea what is going on with these seg faults?

**Comment by idk3** [comment]
@babbush I'm on 0.3.1 with the C++ simulator - could you link to one of the failed Travis runs?

**Comment by babbush** [comment]
Sure, I made a doomed pull request to show you:
https://github.com/quantumlib/OpenFermion-ProjectQ/pull/14

Do you have access to a linux machine? Perhaps you can ssh tunnel into Harvard and look at it?

**Comment by babbush** [comment]
@thomashaener and @damiansteiger : we really need your help figuring out these seg faults. Note that all of our tests pass with projectq 0.3.1, suggesting that something in your last update to projectq broke backwards compatibility.

**Comment by idk3** [comment]
I've been playing with this a little - 0.3.1 is totally fine (all tests pass), but I get segfaults (silent death of my test) with 0.3.4. I've tried commenting things out and restoring lines one at a time to see what could be causing it - one thing that causes it to fail is uncommenting the single-qubit rotations on https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_low_depth_trotter_simulation.py#L131 and L132.

The phase gates are fine, and I have every other gate (except either L131 or L132's Rz, and the phase gate) commented out when I get the problem.

**Comment by idk3** [comment]
Building on this - `S | register[0]`, `H | register[0]`, and `Rz(0) | register[0]` at that point all cause the same problem.

**Comment by idk3** [comment]
OK - it might actually be some interaction of projectq.ops.Ph with other gates (?)

If I comment out `Ph(-zz_angle / 2.) | register`, everything else is OK - is it possible that's changed in some way?

**Comment by damiansteiger** [comment]
1) Can you replicate an error writing the test standalone in ProjectQ?
2) Use the Python simulator as seg faults in C++ might give you an Exception in Python with more information
3) Check the code which uses the simulator, e.g., https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_ffft_test.py#L495 - it tries to deallocate `self.reg` but not sure if it exists in this test class

**Comment by damiansteiger** [comment]
Another thing to correct would be 
```
Ph(-zz_angle / 2.) | register
```
 inhttps://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_low_depth_trotter_simulation.py#L133
It looks like you are applying a single qubit gate to a potentially large quantum register...

**Comment by idk3** [comment]
@damiansteiger so `Ph | register` was something I thought about - it was OK in 0.3.1 but I wondered if it might not have been technically supported. Is there a preferred / better way to do it?

**Comment by damiansteiger** [comment]
`Ph` is only supposed to be applied to a single qubit or a quantum register of size 1. In your case:
```
Ph | register[0]
```

**Comment by idk3** [comment]
Hmm - it fails with `Ph | register[0]` :( I'll try to construct a minimal failing example.

**Comment by babbush** [comment]
Thanks @damiansteiger . I like your suggestion to use the python simulator. Is it possible to do that without reinstalling ProjectQ? How?

**Comment by damiansteiger** [comment]
You can either change your code to run the python simulator (see e.g. https://github.com/ProjectQ-Framework/ProjectQ/blob/develop/projectq/backends/_sim/_simulator_test.py#L69 for how to do that)

or 

if you are running
```
python2.7 -m pytest openfermionprojectq
```
just clone ProjectQ and move the projectq folder into your current folder. Python will then not use the installed projectq but the one in this folder which does not have the C++ simulator installed

**Comment by damiansteiger** [comment]
Try to get them working one by one:
E.g.
https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_ffft_test.py#L497
Should probably be fixed if you change
```
Ph(3 * numpy.pi / 4) | register
```
in https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_ffft_test.py#L508 to 
```
Ph(3 * numpy.pi / 4) | register[0]
```

And remove this as there is not self.reg https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/openfermionprojectq/_ffft_test.py#L495

**Comment by babbush** [comment]
I made these changes but it did not seem to stop the seg fault.

**Comment by damiansteiger** [comment]
I fixed the bugs in FermiLib, see https://github.com/ProjectQ-Framework/FermiLib/tree/bugfix/ph_gate

Updating your fork to this new branch of FermiLib should solve all the problems you experience here.

**Comment by babbush** [comment]
We will not be updating our fork to this branch. We will look at what you did though and try to understand the origin of the problem. But I suspect there is something else going on because tests weren't failing in FermiLib. Also, why do you commit to FermiLib without code reviews now?

**Comment by damiansteiger** [comment]
1) Tests in FermiLib would be failing if we would rerun them with the new ProjectQ version (you can try it out locally)
2) FermiLib performs code review for the develop branch and master branch. Feature branches such as this bugfix get code reviewed when pulled into develop but I just wanted to give you a heads up so you don't waste time finding a fix as the errors in this repo are most certainly copied over from FermiLib. But feel free to find another way to fix the problem

**Comment by babbush** [comment]
Thanks Damian. I somehow thought you linked to develop. My bad. We'll take
a look to see what the problem was.

**Comment by idk3** [comment]
I'll also try again - I made those changes earlier after you suggested them and didn't have luck, but I'll see if pushing to Travis is somehow different.. Obviously I'll be happy if it's just something silly with my machine / some small mistake I made earlier :)

I guess the general takeaway is that `Ph | register` wasn't really defined behaviour - so Ph is a bit different now but still works so long as you apply to a specific qubit.
